/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package beastie.toys.l8n;

import java.util.Arrays;
import java.util.ResourceBundle;

public class App {

    public static FileManager fm;
    public static LocaleUtil localeUtil;

    public static void main(String[] args) {

        fm = FileManager.getInstance(
                Arrays.stream(args)
                        .dropWhile(a -> !"-type".equals(a))
                        .limit(2)
                        .skip(1)
                        .findFirst()
                        .orElse("json")
        );
        localeUtil = LocaleUtil.getInstance(ResourceBundle.getBundle("resource.App"));
        new GameRunner().run();
    }
}
